# Generated by Django 5.2.5 on 2025-09-27 12:55

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_image_path),
        ),
    ]
